### ISSUE TITLE
Devices remain off after successful hack

### ISSUE THREAD

**Issue by dtrail** [ElysiumRL/CustomHackingSystem#1]
When you hack, for example, a computer as part of a mission by jacking in, it will remain turned off as soon as you complete the minigame. There's no way to use it again after that. This applies to all devices that can be hacked in any way. It can break some quests if you do things in the wrong order. In fact you would have to read important mails first and then jack in to hack it.

So far I don't think it's a mod conflict, because I've tried to disable most them in order to check that.

**Comment by ElysiumRL** [comment]
hello, thanks for spotting the issue
the behavior is "normal" (it was planned mostly for access points,and those turn off once completed), however I didn't yet test on computers or other devices.
The ""fix"" is very simple : Minigames/PatternRecognition/InGameMenuController.reds : [Here](https://github.com/ElysiumRL/CustomHackingSystem/blob/ac97fd43c9c32bd5842b3d519ac08fa93be8d9ba/r6/scripts/CustomHackingSystem/Minigames/PatternRecognition/InGameMenuController.reds#L71)

just remove the 3 lines and it should fix it. However, it will obviously stop turning off everything, allowing for multiple hacks in a row.

I'll try to look for a way to make the hack access points only or still leaving other devices powered if they're important, not too sure about the exact definitive behavior of the hack yet

**Comment by dtrail** [comment]
Thank you! That's fine for now.
I'm not very experienced with redscript, but I'm pretty sure there's a way to add some check in order to execute this.TurnOffDevice() only on access points. Or is there no distinction between the different devices available? If not, then I think it could be done via CET. Well, in that case the entire mod would have to be rewritten? Or wait for the redscript guys to find some replacement / add function to distinct devices.

**Comment by dtrail** [comment]
Ah, you removed that already.
