### ISSUE TITLE
Red4Ext Update / Codeware breaks CustomHackingSystem

### ISSUE THREAD

**Issue by dtrail** [ElysiumRL/CustomHackingSystem#2]
Title says it. According to the logs, the part about CustomCodeware doesn't work anymore. Also there's anothert extension now for Red4Ext. That is "Codeware". I guess that part of the mod should be removed, since many of the functions are already defined in Codeware.

**Comment by ElysiumRL** [comment]
Hello
It is indeed the latest version of Codeware that breaks this new version of the mod.

This version of CustomHackingSystem used the old Codeware where every user/modder would have it's own implementation (with sometimes few tweaks) for their own mods. The new Codeware now uses red4ext as a base part and overall is it's own static library that people download (just like a TweakXL or ArchiveXL for instance)

Now fixing it would require a ton of work, and recently (as you might've seen it with the absolute _abysmal_ lack of updates from this github repo), recent schedule have made this mod (and others) relatively inactive (if not completly inactive at all).

It *is* going to be fixed but when... I don't really know. I'll try to find some time for it but considering the fact that I've done some quite large changes to codeware, it could translate in some time to update it to a working state.

**Comment by ElysiumRL** [comment]
Resurrecting this issue from the abyss to say that it's _finally_ fixed. I haven't made a new packaged release yet so it will require to download the source code for now

Tested using Codeware 1.1.4 and RED4ext 1.13.1
